mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('',views.index, name='index'),
    path('q/<int:question_id>',views.detail,name='detail'),
    path('vote/<int:question_id>',views.vote,name='vote'),
    path('results/<int:question_id>',views.results,name='results'),
    
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Question(models.Model):
    
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now()
    datetime.timedelta(days=1)
    
class Choice(models.Model):
    
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self) -> str:
        return self.choice_text

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404
from django.shortcuts import render,get_object_or_404
# Create your views here.
from .models import Question



def index(request):
    q = Question.objects.order_by('-pub_date')[:5]
    #response = ','.join([p.question_text for p in q])
    #template = loader.get_template('index.html')
    context = {
        'questions_list': q
    }
    return render(request,'index.html',context)

def results(request,question_id):
    response = 'You are looking at the results of question %s'
    return HttpResponse(response % question_id)

def detail(request,question_id):
    '''
    try:
        q = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not exist.')
    '''
    q = get_object_or_404(Question,pk=question_id)
    return render(request,'detail.html',{'question': q})

def vote(request,question_id):
    
    return HttpResponse('You are voting for question %s ' % question_id)

polls/templates/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}">

<h3>{{ question }}</h3>



<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

polls/templates/index.html
{% if questions_list %}
    <ul>
        {% for question in questions_list %}
        <li> <a href='/polls/q/{{ question.id }}'> {{ question.question_text}}</a> </li> 
        {% endfor %}
    </ul>
{% else %}
    <p> No polls are available </p>
{% endif %}